name: create-repository.yml
on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
        description: "project language type"
      architecture:
        required: true
        type: string
        description: "project architecture type"
      repository_name:
        required: true
        type: string
        description: "repository name"
    secrets:
      GH_TOKEN:
        required: true

jobs:
  Validate-Repository-name:
    name: "1. Validar nome do repositorio"
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.check_repo.outputs.exists }}

    steps:
      - name: Verificar se o repositório já existe
        id: check_repo
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Lógica final: se encontrar, falha; se não encontrar, passa.
          if gh repo view ${{ github.repository_owner }}/${{ inputs.repository_name }} &>/dev/null; then
            echo "❌ Repositório '${{ inputs.repository_name }}' já existe."
            exit 1 
          else
            echo "✔️ Nome de repositório '${{ inputs.repository_name }}' está disponível."
          fi