name: create-repository.yml
on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
        description: "project language type"
      architecture:
        required: true
        type: string
        description: "project architecture type"
      repository_name:
        required: true
        type: string
        description: "repository name"
    secrets:
      GH_TOKEN:
        required: true

jobs:
  Validate-Repository-name:
    name: "1. Validar nome do repositorio"
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.check_repo.outputs.exists }}

    steps:
      - name: Verificar se o repositório já existe
        id: check_repo
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "--- INICIANDO MODO DE DEPURAÇÃO ---"
          echo "Dono do Repositório (github.repository_owner): ${{ github.repository_owner }}"
          echo "Nome do Repositório para Verificar (inputs.repository_name): ${{ inputs.repository_name }}"
          echo "-------------------------------------"
          echo "Executando 'gh repo view' com saída de erro visível..."
          
          # Executamos o comando e deixamos qualquer erro ser impresso no log
          gh repo view ${{ github.repository_owner }}/${{ inputs.repository_name }}
          
          # Imediatamente após, capturamos o código de saída do comando 'gh'
          EXIT_CODE=$?
          
          echo "-------------------------------------"
          echo "Comando 'gh repo view' concluído."
          echo "O CÓDIGO DE SAÍDA (Exit Code) FOI: $EXIT_CODE"
          echo "-------------------------------------"
          
          if [ $EXIT_CODE -eq 0 ]; then
            echo "DIAGNÓSTICO: O comando foi BEM-SUCEDIDO (código 0). O repositório FOI encontrado."
          else
            echo "DIAGNÓSTICO: O comando FALHOU (código $EXIT_CODE). O repositório NÃO foi encontrado ou houve um erro de permissão/autenticação."
          fi
          
          echo "--- Forçando a falha para análise de logs ---"
          exit 1