name: sta-deploy.yml
on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY:
        required: true
      AWS_SECRET_KEY:
        required: true
      AWS_REGION:
        required: true
      AWS_S3_BUCKET_NAME:
        required: true
      TOKEN_GITHUB:
        required: true
jobs:
  deploy-release-github:
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o artefato
        uses: actions/download-artifact@v4
        with:
          name: nuxt-build
          path: dist/

      - name: Criar Release no GitHub
        uses: actions/create-release@v1
        with:
          tag_name: v1.${{ github.run_number }}
          release_name: "Release v1.${{ github.run_number }}"
          body: "New Version."
          draft: false
          prerelease: false
          files: dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
  Deploy_to_Production:
    runs-on: ubuntu-latest
    needs: deploy-release-github
    environment: Production
    steps:
      - name: Baixar o artefato
        uses: actions/download-artifact@v4
        with:
          name: nuxt-build
          path: dist/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Copy files to the S3 website content bucket
        run: aws s3 sync dist/ s3://${{ secrets.AWS_S3_BUCKET_NAME }} --acl public-read